# permissions for end users to edit nfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: filevault-operator
    app.kubernetes.io/managed-by: kustomize
  name: storage-nfs-editor-role
rules:
- apiGroups:
  - storage.filevault.com
  resources:
  - nfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.filevault.com
  resources:
  - nfs/status
  verbs:
  - get
