# permissions for end users to view nfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: filevault-operator
    app.kubernetes.io/managed-by: kustomize
  name: storage-nfs-viewer-role
rules:
- apiGroups:
  - storage.filevault.com
  resources:
  - nfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.filevault.com
  resources:
  - nfs/status
  verbs:
  - get
